version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sensor_management
    ports:
      - "3306:3306"
    volumes:
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql